[package]
name = "utxo_indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
k256 = { version = "0.11", features = ["ecdsa"] }
anyhow = "1.0.99"
hex = "0.4"
sha2 = "0.10.9"
ripemd = "0.1.3"
