[package]
name = "utxo_indexer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "utxo_indexer"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
bincode = "2.0.1"
bitcoin = "0.32.7"
byteorder = "1.5.0"
clap = { version = "4.5.51", features = ["derive"] }
hex = "0.4.3"
rocksdb = "0.24.0"
