[package]
name = "p2sh"
type = "bin"
authors = ["Distributed Lab"]

[dependencies]
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
bignum = { tag = "v0.7.1", git = "https://github.com/noir-lang/noir-bignum" }
ripemd160 = { tag = "v0.0.2", git = "https://github.com/distributed-lab/noir-ripemd160" }