[workspace]
name = "wrapless-prover"
members = [
    "crates/blocks",
    "crates/p2tr",
    "crates/script",
    "crates/utils",
    "crates/crypto",
    "crates/bvm",
    "crates/sign",
    "app/blocks",
    "app/p2sh",
    "app/p2ms",
    "app/p2pkh",
    "app/p2sh-p2wpkh",
    "app/p2sh-p2wsh",
]
