[workspace]
name = "wrapless-prover"
members = [
    "crates/blocks",
    "crates/p2sh",
    "crates/p2tr",
    "crates/utils",
    "crates/crypto",
    "crates/bvm",
    "crates/sign",
    "app/blocks",
    "app/p2sh",
    "app/p2tr",
]
