[package]
name = "sign"
type = "lib"
authors = ["Distributed Lab"]

[dependencies]
utils = { path = "../utils" }
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }
bignum = { tag = "v0.8.0", git = "https://github.com/noir-lang/noir-bignum" }
crypto = { path = "../../crates/crypto" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }