[package]
name = "p2tr_lib"
type = "lib"
authors = ["Distributed Lab"]

[dependencies]
bignum = { tag = "v0.7.1", git = "https://github.com/noir-lang/noir-bignum" }
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
utils = { path = "../utils" }
crypto = { path = "../crypto" }