address = "bc1pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqenm"
pub_key = "1338827c67f25576325e582db85e859050a2f3e6d349f853774efe6322b7fca1"
script = "1124132413242345435457568579673456335476"
node1 = "1338827c67f25576325e582db85e859050a2f3e6d349f853774efe6322b7fca1"
node2 = "1338827c67f25576325e582db85e859050a2f3e6d349f853774efe6322b7fca1"
