[package]
name = "coins"
type = "bin"

[dependencies]
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }
ripemd160 = { tag = "v0.0.4", git = "https://github.com/distributed-lab/noir-ripemd160" }
utils = { path = "../../../crates/utils" }
crypto = { path = "../../../crates/crypto" }
