const_message_hash = ["0x2c","0xf2","0x4d","0xba","0x5f","0xb0","0xa3","0x0e","0x26","0xe8","0x3b","0x2a","0xc5","0xb9","0xe2","0x9e","0x1b","0x16","0x1e","0x5c","0x1f","0xa7","0x42","0x5e","0x73","0x04","0x33","0x62","0x93","0x8b","0x98","0x24"]

[[coins_database]]
amount = "6094154"
script_pub_key = ["0x76","0xa9","0x14","0xa7","0x93","0x36","0xda","0x4a","0xda","0x61","0x5f","0x0d","0x20","0x3f","0xc4","0xf0","0x95","0x6b","0x8e","0x6e","0xd7","0xf7","0x8b","0x88","0xac"]

[[coins_database]]
amount = "2238282"
script_pub_key = ["0x76","0xa9","0x14","0xa7","0x93","0x36","0xda","0x4a","0xda","0x61","0x5f","0x0d","0x20","0x3f","0xc4","0xf0","0x95","0x6b","0x8e","0x6e","0xd7","0xf7","0x8b","0x88","0xac"]

[[coins_database]]
amount = "1103741"
script_pub_key = ["0x76","0xa9","0x14","0xa7","0x93","0x36","0xda","0x4a","0xda","0x61","0x5f","0x0d","0x20","0x3f","0xc4","0xf0","0x95","0x6b","0x8e","0x6e","0xd7","0xf7","0x8b","0x88","0xac"]

[[own_utxos]]
pub_key = ["0x03","0xfa","0x81","0x48","0x41","0xe2","0x55","0x0b","0x88","0x24","0xa9","0x82","0xe9","0xfc","0x76","0xb6","0xd6","0x7f","0x7d","0x60","0x6f","0x03","0xd5","0x79","0xfe","0xa3","0x42","0x6b","0x1b","0x33","0x3b","0x07","0xd8","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00"]
witness = [
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00"
]

[[own_utxos]]
pub_key = ["0x03","0xfa","0x81","0x48","0x41","0xe2","0x55","0x0b","0x88","0x24","0xa9","0x82","0xe9","0xfc","0x76","0xb6","0xd6","0x7f","0x7d","0x60","0x6f","0x03","0xd5","0x79","0xfe","0xa3","0x42","0x6b","0x1b","0x33","0x3b","0x07","0xd8","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00"]
witness = ["0x30","0x45","0x02","0x21","0x00","0xba","0x29","0x7c","0xea","0x0d","0x9c","0xf8","0xc1","0xcd","0xd3","0xb3","0x4a","0xe1","0xec","0x95","0x9c","0x9b","0x8d","0x46","0x7b","0x41","0xdb","0x0a","0x39","0x54","0x3e","0x32","0x9a","0xe9","0x3a","0x59","0x4e","0x02","0x20","0x0a","0xb1","0xea","0xed","0x72","0x13","0xa9","0x58","0xba","0xe5","0x0e","0x7f","0x4e","0x7a","0xca","0xd5","0x51","0xd6","0x9d","0x7b","0xcb","0x9a","0xec","0xaf","0x36","0xc0","0xa7","0x0f","0xca","0x41","0x7c","0xf9","0x00"]

[[own_utxos]]
pub_key = ["0x03","0xfa","0x81","0x48","0x41","0xe2","0x55","0x0b","0x88","0x24","0xa9","0x82","0xe9","0xfc","0x76","0xb6","0xd6","0x7f","0x7d","0x60","0x6f","0x03","0xd5","0x79","0xfe","0xa3","0x42","0x6b","0x1b","0x33","0x3b","0x07","0xd8","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00"]
witness = ["0x30","0x45","0x02","0x21","0x00","0xba","0x29","0x7c","0xea","0x0d","0x9c","0xf8","0xc1","0xcd","0xd3","0xb3","0x4a","0xe1","0xec","0x95","0x9c","0x9b","0x8d","0x46","0x7b","0x41","0xdb","0x0a","0x39","0x54","0x3e","0x32","0x9a","0xe9","0x3a","0x59","0x4e","0x02","0x20","0x0a","0xb1","0xea","0xed","0x72","0x13","0xa9","0x58","0xba","0xe5","0x0e","0x7f","0x4e","0x7a","0xca","0xd5","0x51","0xd6","0x9d","0x7b","0xcb","0x9a","0xec","0xaf","0x36","0xc0","0xa7","0x0f","0xca","0x41","0x7c","0xf9","0x00"]

