[package]
name = "proof_of_reserve"
type = "bin"

[dependencies]
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "merkle-trees-v0.0.1", directory = "packages/merkle-trees" }
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
utils = { path = "../../crates/utils" }
