last_block_hash = "000000006a625f06636b8bb6ac7b960a8d03705d1ace08b1a19da3fdcc99ddbd"

[[blocks]]
version = "1"
prev_block = "0000000000000000000000000000000000000000000000000000000000000000"
merkle_root = "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b"
timestamp = "1231006505"
bits = "486604799"
nonce = "2083236893"

[[blocks]]
version = "1"
prev_block = "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f"
merkle_root = "0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098"
timestamp = "1231469665"
bits = "486604799"
nonce = "2573394689"

[[blocks]]
version = "1"
prev_block = "00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048"
merkle_root = "9b0fc92260312ce44e74ef369f5c66bbb85848f2eddd5a7a1cde251e54ccfdd5"
timestamp = "1231469744"
bits = "486604799"
nonce = "1639830024"
