[package]
name = "utils"
type = "lib"
authors = ["Distributed Lab"]

[dependencies]
bignum = { tag = "v0.8.0", git = "https://github.com/noir-lang/noir-bignum" }
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }