[package]
name = "bvm"
type = "lib"
authors = ["Distributed Lab"]

[dependencies]
utils = { path = "../utils" }
sign = { path = "../sign" }
ripemd160 = { tag = "v0.0.3", git = "https://github.com/distributed-lab/noir-ripemd160" }
sha1 = { tag = "v0.1.0", git = "https://github.com/zac-williamson/sha1" }
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }