address = ["243", "159", "214", "229", "26", "173", "136", "246", "244", "206", "106", "184", "130", "114", "121", "207", "255", "185", "34", "102"]

[block]
version = "1"
prev_block = "0000000000000000000000000000000000000000000000000000000000000000"
merkle_root = "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b"
timestamp = "1231006505"
bits = "486604799"
nonce = "2083236893"
