[package]
name = "blocks_lib"
type = "lib"
authors = ["Distributed Lab"]

[dependencies]
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
bignum = { tag = "v0.6.1", git = "https://github.com/noir-lang/noir-bignum" }
convert = { path = "../utils" }
