[package]
name = "p2pkh"
type = "bin"

[dependencies]
bvm = { path = "../../crates/bvm" }
sign = { path = "../../crates/sign" }
utils = { path = "../../crates/utils" }
script = { path = "../../crates/script" }

