[package]
name = "utxos_tree"
type = "bin"

[dependencies]
utils = { path = "../../../crates/utils" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-nightly.20251104", directory = "barretenberg/noir/bb_proof_verification" }