[package]
name = "crypto"
type = "lib"
authors = ["Distributed Lab"]

[dependencies]
bignum = { tag = "v0.8.0", git = "https://github.com/noir-lang/noir-bignum" }
bignum2 = {tag = "v0.8.0-2", git = "https://github.com/zkpassport/noir-bignum"}
utils = { path = "../utils" }
noir_ecdsa = { tag = "v0.2.9", git = "https://github.com/zkpassport/noir-ecdsa" }
bigcurve = {tag = "v0.11.0-1", git = "https://github.com/zkpassport/noir_bigcurve"}
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }