[package]
name = "crypto"
type = "lib"
authors = ["Distributed Lab"]

[dependencies]
bignum = { tag = "v0.7.1", git = "https://github.com/noir-lang/noir-bignum" }
bignum2 = {tag = "v0.7.3-2", git = "https://github.com/zkpassport/noir-bignum"}
utils = { path = "../utils" }
noir_ecdsa = { tag = "v0.2.7", git = "https://github.com/zkpassport/noir-ecdsa" }
bigcurve = {tag = "v0.9.0-1", git = "https://github.com/zkpassport/noir_bigcurve"}